name: Feature Request
description: Suggest an idea for the Amplify Studio
labels: ["pending-triage"]

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to submit a feature request! Try to include as much information as you can.

        > **Note**: If your question is regarding the AWS Amplify Hosting, Amplify UI, or Amplify CLI, refer to
        > - For **Amplify Hosting** issues, visit [amplify-hosting](https://github.com/aws-amplify/amplify-hosting/issues/new/choose)
        > - For **Amplify UI** issues, visit [amplify-ui](https://github.com/aws-amplify/amplify-ui/issues/new/choose)
        > - For **Amplify CLI** issues, visit [amplify-cli](https://github.com/aws-amplify/amplify-cli/issues/new/choose)

  - type: textarea
    attributes:
      label: Describe the feature you'd like to request
      description: |
        A clear and concise description of what you want to happen. Please include **any related issues**, documentation, etc.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe your use case and how the feature would improve your experience.
      description: |
        A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      description: |
        A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional context
      description: |
        Add any other use cases or context about the feature request here. Please include any prototype, workaround, reference implementation, etc.
