blank_issues_enabled: true
contact_links:
  - name: Bug Report
    url: https://docs.aws.amazon.com/awssupport/latest/user/case-management.html#creating-a-support-case
    about: Bug reports should be raised with the AWS Support team
  - name: Have a question? Join the Amplify Community Discord Server
    url: https://discord.gg/amplify 
    about: Ask questions and discuss with other community members
  - name: Amplify Studio Documentation
    url: https://docs.amplify.aws/react/tools/console/
    about: Official documentation for Amplify Studio